#Aim: Write a program to implement arithmetic operators +-*/%//**
a = int(input('Enter your first number: '))
b = int(input('Enter your second number: '))
print("Addition: ",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Float division:",a/b)
print("Integer division:",a//b)
print("Remainder:",a%b)
print("Exponent(x^y):",a**b)
print("Exponent(y^x):",b**a)