a = int(input('Enter your first number: '))
b = int(input('Enter your second number: '))
print("Addition: ",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Float division:",a/b)
print("Integer division:",a//b)
print("Quotient:",a%b)